# Nombre del microservicio
spring.application.name=backend-core

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (MONGODB)
# ==========================================
# Si Railway tiene la variable 'URL_MONGO_NUBE', la usará. 
# De lo contrario, usará localhost.
#spring.data.mongodb.uri=${URL_MONGO_NUBE:mongodb://localhost:27017/db_gestion_procesos}
spring.mongodb.uri=${URL_MONGO_NUBE:mongodb://localhost:27017/db_gestion_procesos}
# ==========================================
# CONFIGURACIÓN DE RED (PUERTO)
# ==========================================
server.port=${PORT:8080}
#fkflkgfogfkogfogf
# ==========================================
# LOGS DE DEPURACIÓN (MODO DETECTIVE)
# ==========================================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# 2. Silenciar el "ruido" del driver de Mongo (¡MUY IMPORTANTE en Railway!)
logging.level.org.mongodb.driver.cluster=WARN
logging.level.org.mongodb.driver.connection=WARN

# 3. Desactivar el reporte de autoconfiguración inicial
logging.level.org.springframework.boot.autoconfigure.logging=INFO

# 4. Web y servidor en modo estándar
logging.level.org.apache.tomcat=INFO
logging.level.org.springframework.web=INFO

#lgbmlbbt


# ==========================================
# CONFIGURACIÓN JWT (NUEVO)
# ==========================================
# Genera una llave secreta larga y aleatoria (base64)
jwt.secret=404e635266556a586e3272357538782F413f4428472b4b6250655368566d5971
# Tiempo de expiración del token (ej. 24 horas en milisegundos)
jwt.expiration=86400000

management.endpoints.web.exposure.include=mappings




# Configuración de AWS S3
aws.access-key=${AWS_ACCESS_KEY_ID:AKIA6CFIXEP2BJ7E57WF}aws.secret-key=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
aws.secret-key=${AWS_SECRET_ACCESS_KEY:CDriEoEXLqooOLg/IYSbHVFJ0F8jgr6HHTNb0JXQ}#aws.secret.access.key=TU_SECRET_ACCESS_KEY_REAL

aws.region=${AWS_REGION:us-east-2}
aws.s3.bucket.name=${AWS_BUCKET_NAME:uagrm-gestion-archivos-beimar}


spring.data.mongodb.auto-index-creation=true

# Tamaño máximo permitido para un solo archivo
spring.servlet.multipart.max-file-size=10MB

# Tamaño máximo permitido para la petición completa (incluyendo texto y múltiples archivos)
spring.servlet.multipart.max-request-size=50MB



# Cambiamos el puerto de 1234 a 5000
spring.ai.openai.base-url=http://localhost:5000
spring.ai.openai.api-key=local-key
spring.ai.openai.chat.options.model=gemma-2-2b-it